### ISSUE TITLE
Full Readme but no source? and no pypi release?

### ISSUE THREAD

**Issue by JokersCat** [GalaxzyDev/NoCap.py#2]

**Comment by GalaxzyDev** [comment]
In the repo description, it says "Coming Soon." Just give it a another day or two.

**Comment by JokersCat** [comment]
Oh sorry i dont saw it sorry for blaming you 😅. And yeah I wait no problem

**Comment by GalaxzyDev** [comment]
Alright, now worries.

**Comment by JokersCat** [comment]
Hey just wanted to ask how it’s going?

**Comment by GalaxzyDev** [comment]
Its going alright, its been delayed, since I need to update Deadcord, I will try to get it out soon, but an ETA is undetermined for now.

**Comment by JokersCat** [comment]
Okay 👍

**Comment by JokersCat** [comment]
Hey sorry to contact you again 😅. I just wanted to ask if the release comes closer or is it getting delayed a bit more m?

**Comment by GalaxzyDev** [comment]
I'm am not sure, I will prioritize this project once the new Deadcord update is ready.

**Comment by JokersCat** [comment]
Okay thx for the fast answer 😊

**Comment by JokersCat** [comment]
And I’m looking forward to the upcoming releases

**Comment by JokersCat** [comment]
Hey it’s me again. 👋
So  how is it going? are you still working on this project? And a are some captchas like Funcaptcha planned?

**Comment by GalaxzyDev** [comment]
Yes, I still plan to release this, as soon as the captcha update for Deadcord comes out.

**Comment by JokersCat** [comment]
Nice 👍

**Comment by Anydex** [comment]
This isnt going to come out. He's made that clear.

**Comment by GalaxzyDev** [comment]
@Anydex 

How so? I stay true to my word, but at the moment I have higher priorities. I am one person providing these things for free. What are you contributing here?

**Comment by Anydex** [comment]
what bro shush

**Comment by Anydex** [comment]
> @Anydex
> 
> How so? I stay true to my word, but at the moment I have higher priorities. I am one person providing these things for free. What are you contributing here?

I literally dont care

**Comment by GalaxzyDev** [comment]
Alright, then why bother creating this thread if you didn't care. Go fuck around somewhere else.
